### ISSUE TITLE
demo运行错误

### ISSUE THREAD

**Issue by xjianhero** [huobiapi/REST-Java-demo#8]
![image](https://user-images.githubusercontent.com/12026417/49427264-d3ea9780-f7dd-11e8-890f-ef4769df5ada.png)

**Comment by lixiujunj2ee** [comment]
我也遇到同样的错误提示

**Comment by huobiapi** [comment]
由于地址被墙，请您使用境外的云服务器访问，不建议使用各种形式的代理连接API
